dare = [
    "Take an embarrassing selfie and post it as your profile picture.",
    "Remove your socks with your teeth.",
    "Go next door with a measuring cup and ask for a cup of sugar.",
    "Let the group choose an item for you to brush your teeth with.",
    "Write your name on the floor with your tongue.",
    "Stick a Hot Cheeto in your nose, and leave it there for five minutes.",
    "Open your front door and howl like a wolf for 30 seconds.",
    "Let the person to your right put duct tape on any part of your body they choose and rip it off.",
    "Put a bunch of honey on your nose and coat it with flour.",
    "Until the next round, talk super loud, like nobody can hear you.",
    "Call your crush.",
    "Take a shot of pickle juice.",
    "Talk to a pillow like it's your crush.",
    "Pretend you're a bird and eat cereal off the floor using only your mouth.",
    "Make out with your hand.",
    "Let someone else style your hair and keep it that way for the rest of the day.",
    "Use a brush like you're talking into a microphone each time you speak.",
    "Color one of your front teeth black. (Eyeliner works!)",
    "Pick your friend's nose.",
    "Fake cry.",
    "Make repulsive sounds while eating and drinking.",
    "Cross your eyes when talking.",
    "Talk without closing your mouth.",
    "Act like an animal of the group's choosing.",
    "Get into a debate with a wall.",
    "Squirt your face with a squirt gun continuously while talking.",
    "See how many grapes you can stuff in your mouth.",
    "Hiccup in between each word.",
    "Burp the alphabet.",
    "Draw on your face with permanent marker.",
    'Run around outside yelling, "I have lice!"',
    "Stop a car that is going down the road and tell them that their wheels are turning.",
    "Lick a car tire.",
    "Lick the bottom of your shoe.",
    'Text someone "hey." Every time they respond, say "hey." Do this 10 times. For the 11th time, reply with "hi."',
    "Dip your finger in the toilet, and then kiss that finger.",
    "Make a hand puppet by drawing a face on your hand, and use your hand to say what you want to say.",
    "Let everyone look through your search history for two minutes.",
    "Coat your hands in food coloring and don't wash them off for 10 minutes.",
    "Skype/FaceTime someone and pick your nose during the conversation.",
    "Remove your underwear and throw it in the bin.",
    "Let a person in the group put a leash on you and walk you down the street.",
    "Spin around 10 times and try to walk straight.",
    "Eat a raw egg.",
    "Let the group choose three random things from the fridge and mix them together. Then you have to eat the mixture.",
    "Stand up and do star jumps until your next turn.",
    "Rub your armpits and then smell your fingers.",
    "Dig through the trash and name everything you find.",
    "Stand in the backyard and yell at the top of your lungs, “Nooooo! I was adopted!”",
    "Go outside in the driveway and do the disco without music.",
    "Call a car part store and tell them that you need a part for your Model T.",
    "Take a selfie with the toilet and post it online.",
    "Sniff everyone's feet and rank them in order of freshest to stinkiest.",
    "Call a NY-style pizza place and ask them what the difference is between NY pizza and “real” pizza.",
    "Open your front door and loudly sing “Hallelujah!”",
    "Go outside and pretend you're cutting the grass with an invisible mower.",
    "Call a pizza place and ask if they use cruelty-free wheat in their dough.",
    "Call your mom and tell her you can't find a girlfriend in a very panicked voice.",
    "Wear your pants over your bottoms for the rest of the game.",
    "Call the library and ask if they carry a dictionary that translates British to American.",
    "Send a Snapchat of you pretending to cry because you just found out you were adopted.",
    'Go on Facebook and write "How do you spell "facebook"?" as your status.',
    "Sniff the armpit of the person next to you, and describe what it smells like to the entire group.",
    "Go outside and try to summon the rain.",
    'Sing the "Star-Spangled Banner" in a British accent.',
    "Take a picture of a tampon and post it on Instagram.",
    "Call a random number, and when someone picks up, immediately start singing the national anthem.",
    "Call Target and ask them if they deliver popcorn.",
    "Call McDonald's and ask if they sell Whoppers.",
    "Call a pizza shop and ask if you can return a pizza.",
    "Call a car dealership and ask if they have any horse buggies in stock.",
    "Change your relationship status on Facebook to it's complicated.\"",
    "Call Macy's and tell them you're interested in buying them.",
    "Sing instead of speaking for the next two rounds of the game.",
    'Call a random number and sing "Happy Birthday."',
    "Call a Chinese restaurant and ask if they have sushi.",
]
