truth = [
    "What is your favourite type of chocolate?",
    "What is your favourite brand of chocolate?",
    "Who is your crush?",
    "Who is your best friend?",
    "Who is your worst enemy?",
    "What is the first thing in your search history?",
    "Have you ever eaten a bogey?",
    "Have you ever peed in the pool?",
    "Who dresses the worst in the year 7?",
    "Do you have an imaginary friend?",
    "If you could do 1 thing what would  it be?",
    'Did your parents ever give you the "birds and the bees" talk?',
    "What is your guilty pleasure?",
    "Has anyone ever walked in on you in the bathroom?",
    "What is your worst habit?",
    "Who would you hate to see naked?",
    "How long have you gone without a shower?",
    "If you could only text one person for the rest of your life, but you could never talk to that person face-to-face, who would that be?",
    "How long have you gone without brushing your teeth?",
    "What's one thing you would never eat on a first date?",
    "What have you seen that you wish you could unsee?",
    "If you could be reincarnated into anyone's body, who would you want to become?",
    "If you switched genders for the day, what would you do?",
    "What's one food that you will never order at a restaurant?",
    "What's the worst weather to be stuck outside in if all you could wear was a bathing suit?",
    "If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?",
    "What's the most useless piece of knowledge you know?",
    "What did you learn in school that you wish you could forget?",
    "Is it better to use shampoo as soap or soap as shampoo?",
    "If you ran out of toilet paper, would you consider wiping with the empty roll?",
    "What would be the worst part about getting pantsed in front of your crush?",
    "If you could only use one swear word for the rest of your life, which one would you choose?",
    "What's the best thing to say to your friend that would be the worst thing to say to your crush?",
    "Who do you think is the Beyonce of the group?",
    "Would you rather eat dog food or cat food?",
    "If you had nine lives, what would you do that you wouldn't do now?",
    "If you could play a prank on anyone without getting caught, who would you play it on?",
    "What would the prank be?",
    "Have you ever pretended to like a gift? How did you pretend?",
    "Would you rather not shower for a month, or eat the same meal every day for a month?",
    "What animal most closely resembles your eating style?",
    "If you could choose to never sweat for the rest of your life or never have to use the bathroom, which would you choose?",
    "If you could spend every waking moment with your girlfriend or boyfriend, would you?",
    "Do you currently have a crush on anyone?",
    "Describe what your crush looks like.",
    "What is your crush's personality like?",
    "Is there anything about your life you would change?",
    "Who do you hate, and why?",
    "What's your biggest pet peeve?",
    "How many people have you kissed?",
    "What's your biggest turn-on?",
    "If you could date anyone in the world, who would you date?",
    "Would you rather be skinny and hairy or fat and smooth?",
    "Who would you ask to prom if you could choose anyone?",
    "Describe your perfect date.",
    "Would you ever date two people at once if you could get away with it?",
    "You have to delete every app on your except for five. Name the five you would keep.",
    "Have you ever gotten mad at a friend for posting an unflattering picture of you?",
    "Have you ever had a crush on a teacher?",
    "Have you ever sent someone the wrong text?",
    "Have you ever cursed at your parents? Why?",
    "Who do you think is the cutest person in your class?",
    "What is the most attractive feature on a person?",
    "What the biggest deal-breaker for you?",
    "How far would you go on a first date?",
    "Have you ever regretted something you did to get a crush's attention?",
    "Would you ever be mean to someone if it meant you could save your close friend from embarrassment?",
    "Of the people at our school, who do you think would make the best president?",
    "If we didn't have a dress code, what would you wear to school that you can't wear now?",
    "Describe what makes someone husband or wife material.",
    "If you could make $1 million, would you drop out of school?",
    "What is your worst habit?",
    "What's one thing you do that you don't want anyone to know about?",
    "Do you frequently stalk anyone on social media? Who?",
]
